#!/usr/bin/env python

import md5

m = md5.new()
i = 1

print md5.new("abcdef609043").hexdigest()

with open("../input/04.txt") as fileobj:
	for word in fileobj:  
		#for ch in word:
		#word=word.rstrip()
		word="abcdef"
		while True:
			m.update("{}{}".format(word,i))
			if m.hexdigest()[:5] == '0000':
				print word,i
				print m.hexdigest()
				break
			i+=1 
